name: Measure coverage - Java 16

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.16
        uses: actions/setup-java@v1
        with:
          java-version: 1.16
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew testCoverage
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80