name: codecov

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Node.js dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Lint project
        run: npm run lint
      - name: Test project
        run: npm run test
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash) -s coverage/ -t "732e817d-1a2e-44f5-9468-e6ed62033a87"
